#ifndef EASY_DISPLAY_STATUS_H
#define EASY_DISPLAY_STATUS_H

typedef enum {
    EASY_DEVICE_OK = 0,
    EASY_DEVICE_ERROR_PARAM,
    EASY_DEVICE_ERROR_STATE,
    EASY_DEVICE_ERROR_NOT_READY,
    EASY_DEVICE_ERROR_BUSY,
    EASY_DEVICE_ERROR_IO,
    EASY_DEVICE_ERROR_NOT_SUPPORTED,
} easy_device_status_t;

#endif

